---
# Source: eks-node-monitoring-agent/crds/eks.amazonaws.com_nodediagnostics.yaml
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.5
  name: nodediagnostics.eks.amazonaws.com
spec:
  group: eks.amazonaws.com
  names:
    kind: NodeDiagnostic
    listKind: NodeDiagnosticList
    plural: nodediagnostics
    singular: nodediagnostic
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: |-
          The name of the NodeDiagnostic resource is meant to match the name of the
          node which should perform the diagnostic tasks
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              logCapture:
                description: |-
                  LogCapture is a definition for a diagnostic task that will package relevant
                  logs and stats into a tarball and deliver it to a provided destination.
                properties:
                  categories:
                    default:
                    - All
                    description: Categories are log source groups for the LogCapture
                      task.
                    items:
                      description: |-
                        LogCategory is a grouping of log sources to read from when performing a
                        LogCapture task.
                      enum:
                      - Base
                      - Device
                      - Networking
                      - Runtime
                      - System
                      - All
                      type: string
                    type: array
                  destination:
                    description: UploadDestination is a URL describing where to deliver
                      a diagnostic artifact.
                    type: string
                required:
                - destination
                type: object
            type: object
          status:
            properties:
              captureStatuses:
                items:
                  description: CaptureStatus describes the type and state of a capture
                    task.
                  properties:
                    state:
                      properties:
                        completed:
                          properties:
                            finishedAt:
                              format: date-time
                              type: string
                            message:
                              type: string
                            reason:
                              type: string
                            startedAt:
                              format: date-time
                              type: string
                          required:
                          - finishedAt
                          - message
                          - reason
                          - startedAt
                          type: object
                        running:
                          properties:
                            startedAt:
                              format: date-time
                              type: string
                          required:
                          - startedAt
                          type: object
                      type: object
                    type:
                      description: The set of diagnostic tasks supported by the NodeDiagnostic
                        resource.
                      type: string
                  required:
                  - state
                  - type
                  type: object
                type: array
              conditions:
                items:
                  description: Condition aliases the upstream type and adds additional
                    helper methods
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}

---
# Source: eks-node-monitoring-agent/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eks-node-monitoring-agent
  namespace: kube-system
  labels:
    app.kubernetes.io/name: eks-node-monitoring-agent
    app.kubernetes.io/instance: eks-node-monitoring-agent
    app.kubernetes.io/version: "1.5.1"
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: EKS
---
# Source: eks-node-monitoring-agent/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks-node-monitoring-agent
  labels:
    app.kubernetes.io/name: eks-node-monitoring-agent
    app.kubernetes.io/instance: eks-node-monitoring-agent
    app.kubernetes.io/version: "1.5.1"
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: EKS
rules:
  # monitoring permissions
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
  # nodediagnostic permissions
- apiGroups: ["eks.amazonaws.com"]
  resources: ["nodediagnostics"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["eks.amazonaws.com"]
  resources: ["nodediagnostics/status"]
  verbs: ["patch"]
---
# Source: eks-node-monitoring-agent/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-node-monitoring-agent
  labels:
    app.kubernetes.io/name: eks-node-monitoring-agent
    app.kubernetes.io/instance: eks-node-monitoring-agent
    app.kubernetes.io/version: "1.5.1"
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: EKS
roleRef:
  kind: ClusterRole
  name: eks-node-monitoring-agent
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: eks-node-monitoring-agent
  namespace: kube-system
---
# Source: eks-node-monitoring-agent/templates/daemonset.yaml
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: eks-node-monitoring-agent
  namespace: kube-system
  labels:
    app.kubernetes.io/name: eks-node-monitoring-agent
    app.kubernetes.io/instance: eks-node-monitoring-agent
    app.kubernetes.io/version: "1.5.1"
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: EKS
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: eks-node-monitoring-agent
      app.kubernetes.io/instance: eks-node-monitoring-agent
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eks-node-monitoring-agent
        app.kubernetes.io/instance: eks-node-monitoring-agent
        app.kubernetes.io/version: "1.5.1"
        app.kubernetes.io/component: controller
        app.kubernetes.io/managed-by: EKS
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values:
                - fargate
                - auto
              - key: sagemaker.amazonaws.com/compute-type
                operator: NotIn
                values:
                - hyperpod
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      tolerations:
        - operator: Exists
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      serviceAccountName: eks-node-monitoring-agent
      hostNetwork: true
      hostPID: true
      containers:
        - name: eks-node-monitoring-agent
          image: {{ .Image }}
          imagePullPolicy: Always
          args:
            - --probe-address=:8002
            - --metrics-address=:8003
            - --pprof-address=:8082
            - --verbosity=5
          env:
            - name: HOST_ROOT
              value: "/host"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8002
          resources:
            limits:
              cpu: 250m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 30Mi
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
            privileged: true
          volumeMounts:
            - name: host-root
              mountPath: /host
      volumes:
        - name: host-root
          hostPath:
            path: /
---
# Source: eks-node-monitoring-agent/templates/dcgm-daemonset.yaml
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: dcgm-server
  namespace: kube-system
  labels:
    k8s-app: dcgm-server
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: dcgm-server
      version: v1
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: dcgm-server
        version: v1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - g3.16xlarge
                - g3.4xlarge
                - g3.8xlarge
                - g3s.xlarge
                - g4dn.12xlarge
                - g4dn.16xlarge
                - g4dn.2xlarge
                - g4dn.4xlarge
                - g4dn.8xlarge
                - g4dn.metal
                - g4dn.xlarge
                - g5.12xlarge
                - g5.16xlarge
                - g5.24xlarge
                - g5.2xlarge
                - g5.48xlarge
                - g5.4xlarge
                - g5.8xlarge
                - g5g.16xlarge
                - g5g.2xlarge
                - g5g.4xlarge
                - g5g.8xlarge
                - g5g.metal
                - g5g.xlarge
                - g5.xlarge
                - g6.12xlarge
                - g6.16xlarge
                - g6.24xlarge
                - g6.2xlarge
                - g6.48xlarge
                - g6.4xlarge
                - g6.8xlarge
                - g6e.12xlarge
                - g6e.16xlarge
                - g6e.24xlarge
                - g6e.2xlarge
                - g6e.48xlarge
                - g6e.4xlarge
                - g6e.8xlarge
                - g6e.xlarge
                - g6f.2xlarge
                - g6f.4xlarge
                - g6f.large
                - g6f.xlarge
                - g6.xlarge
                - g7e.12xlarge
                - g7e.24xlarge
                - g7e.2xlarge
                - g7e.48xlarge
                - g7e.4xlarge
                - g7e.8xlarge
                - gr6.4xlarge
                - gr6.8xlarge
                - gr6f.4xlarge
                - p2.16xlarge
                - p2.8xlarge
                - p2.xlarge
                - p3.16xlarge
                - p3.2xlarge
                - p3.8xlarge
                - p3dn.24xlarge
                - p4d.24xlarge
                - p4de.24xlarge
                - p5.48xlarge
                - p5.4xlarge
                - p5e.48xlarge
                - p5en.48xlarge
                - p6-b200.48xlarge
                - p6-b300.48xlarge
                - p6e-gb200.36xlarge
                - p6e-gb300.36xlarge
                - p6e-gb300r.36xlarge
              - key: eks.amazonaws.com/compute-type
                operator: NotIn
                values:
                - fargate
                - auto
              - key: sagemaker.amazonaws.com/compute-type
                operator: NotIn
                values:
                - hyperpod
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      containers:
        - name: eks-node-monitoring-agent-dcgm
          image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/observability/dcgm-exporter:4.4.2-4.7.1-ubuntu22.04
          command: ["/bin/sh"]
          args: ["-c", "nv-hostengine -n -b ALL || true; sleep infinity"]
          ports:
          - containerPort: 5555
            hostPort: 5555
          securityContext:
            privileged: true
